apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-core
  namespace: argo
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nextcloud
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 6.0.0
    helm:
      releaseName: nextcloud
